#!/bin/sh


# 9/18/13
# Use xrandr to change monitor resolution and manage dual monitors.
#xrandr --output VGA1 --mode 1920x1080 --pos 1366x0 --output LVDS1 --mode 1366x768 --pos 0x0
xrandr --output CRT1 --off --output DFP1 --off --output LVDS --mode 1366x768 --pos 0x0

